services:
  ssh-borg-serve:
    image: ghcr.io/arian04/borg-serve:latest
    build:
      context: .
    volumes:
      - ./authorized_keys:/config/ssh/authorized_keys:ro
      - ./repos/:/data/repos
    ports:
      - 22022:22
    restart: unless-stopped
